### ISSUE TITLE
Flipper

### ISSUE THREAD

**Issue by bencagri** [Teknasyon-Teknoloji/desk360-react-native-sdk#1]
Hi, thx for this remarkable package.

isn't there any way without removing flipper from project?

**Comment by nazrdogan** [comment]
+1

**Comment by nazrdogan** [comment]
I revisited this issue today again.  and got it working along with the Flipper. need to edit `Podfile` 

Add this to the application target inside Podfile. and if the application uses Firebase`$RNFirebaseAsStaticFramework = true` it's also required on top of Podfile. our flipper version is 0.149.
 
    $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
      'CocoaAsyncSocket', 'ComponentKit', 'Flipper-DoubleConversion',
      'Flipper-Glog', 'Flipper-PeerTalk',
      'CocoaLibEvent', 'OpenSSL-Universal', 'Flipper-Boost-iOSX', 'Flipper-Fmt']

    pre_install do |installer|
      Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
      installer.pod_targets.each do |pod|
          if $static_framework.include?(pod.name)
            def pod.build_type;
              Pod::BuildType.static_library
            end
          end
        end
    end

**Comment by befy** [comment]
To avoid pod caches delete lock file in the root direction of your project:

```bash 
$ rm -rf Podfile.lock
```

Adding these lines to your _Podfile_ will make your project to **successfully** compile with Flipper and Desk360 SDK.

```ruby
 use_flipper!({ 'Flipper' => '0.150.0' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
       config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
     end
    end
  end
```

And then install with the latest versions:

```bash 
$ pod install --repo-update
```

**Comment by dinncer** [comment]
Please let us know if the comment above not solved issue.
