### ISSUE TITLE
lib folder is missing - Metro packager cannot find lib folder and throwing red screen

### ISSUE THREAD

**Issue by nazrdogan** [Teknasyon-Teknoloji/desk360-react-native-sdk#3]
this might be resolved when publishing to npm. As a workaround, I manually edited package.json to `"main": "src/index",` to get working properly.

**Comment by omerfarukoner** [comment]
Thanks @nazrdogan. Editing package.json to `"main": "src/index"` worked for me.

**Comment by dinncer** [comment]
We are going to publish a new release that will fix this issue.
Thank you for letting us know this issue.
